---
name: "SLURM"
partition: "normal"
job-name: "box_random_tsac_entire"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 999
gpus_per_rep: 1
scheduler: horeka
sbatch_args:
  gres: "gpu:full:4"
#  account: "hk-project-p0022232"

experiment_copy_src:
  - "../" # RL Code base
#  - "../../fancy_gymnasium/" # fancy_gym
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: box_random_tsac_entire
import_path: "./shared.yaml"
import_exp: "box_random_tsac_entire"

# cw2 config
repetitions: 4      # Number of repetitions, each with different random seed, 4 for test, 20 for paper
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 50000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 4
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations

#list:
#  sampler:
#    args:
#      num_env_train: [1, 2, 3]
#      min_length: [1]
#      step_length: [64]

grid:
#  agent:
#    args:
#      random_critic_index_number: [0.2, 0.4, 0.6, 0.8]

#      target_update_interval: [1, 100]
#      lr_policy: [2.5e-4, 2.0e-4, 1.5e-4, 1.0e-4, 0.5e-4]
#      lr_critic: [6e-5, 3e-5, 2.5e-5, 2.0e-5, 1.5e-5]
#      training_times_critic: [1, 2, 3, 4]
#      batch_size: [128, 256, 512, 1024]
#      entropy_penalty_coef: [0.0, 0.02, 0.002, 0.2]
#      discount_factor: [1.0, 0.98]
#      random_policy_index_number: [10, 20, 30, 40])
  sampler:
    args:
#      num_env_train: [4, 5, 6, 7, 8, 9, 10, 11, 12]
#      min_length: [1, 4]
      step_length: [1]
#  replay_buffer:
#    args:
#      buffer_size: [1000, 2000, 3000, 4000, 5000, 10000, 15000, 20000]
#  policy:
#    args:
#      mean_net_args:
#        layer_norm: [false, true]
#        avg_neuron: [256, 512]
#        num_hidden: [2, 4]
#      variance_net_args:
#        layer_norm: [false, true]
#        avg_neuron: [64, 128, 256, 512]
  critic:
    args:
      update_rate: [5.0e-3, 1.0]
#      net_args:
#        n_embd: [128, 256]
#        n_layer: [1, 2, 3, 4]
#        n_head: [1, 2, 4, 8]