---
name: "SLURM"
partition: "dev_cpuonly"
job-name: "box_pushing_nrsac_entire"
num_parallel_jobs: 0
ntasks: 1
cpus-per-task: 152
time: 2899
cpus_per_rep: 38
scheduler: cpu_distribute

experiment_copy_src:
  - "../" # RL Code base
#  - "../../fancy_gymnasium/" # fancy_gym
experiment_copy_auto_dst: "../../CODE_COPY/"
---
name: box_pushing_nrsac_entire
import_path: "./shared.yaml"
import_exp: "box_pushing_nrsac_entire"

# cw2 config
repetitions: 4      # Number of repetitions, each with different random seed, 4 for test, 20 for paper
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 50000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 4
      num_env_test: 38
      episodes_per_train_env: 1
      episodes_per_test_env: 4
  projection:
    args:
      total_train_steps: *iterations

#list:
#  agent:
#    args:
#      lr_policy: [1e-3, 3e-4, 1e-4, 3e-5]
#      training_times_critic: [1, 2, 3, 4]
#        num_hidden: [1, 2, 1, 2]